//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowdevApi.Excecao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensExcecao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensExcecao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrowdevApi.Excecao.MensagensExcecao", typeof(MensagensExcecao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido que um usuário exclua a si mesmo.
        /// </summary>
        public static string AUTO_EXCLUSAO {
            get {
                return ResourceManager.GetString("AUTO_EXCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com este e-mail..
        /// </summary>
        public static string EMAIL_JA_EXISTE {
            get {
                return ResourceManager.GetString("EMAIL_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou senha inválido.
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ser vazio.
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido.
        /// </summary>
        public static string ID_INVALIDO {
            get {
                return ResourceManager.GetString("ID_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id vazio.
        /// </summary>
        public static string ID_VAZIO {
            get {
                return ResourceManager.GetString("ID_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser vazio.
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O refresh token não pode ser vazio.
        /// </summary>
        public static string REFRESH_TOKEN_VAZIO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem token.
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida. A senha deve ter no mínimo 8 caracteres, possuir letra maiúscula, letra minúscula, número e símbolo.
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser vazia.
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão expirada.
        /// </summary>
        public static string SESSAO_EXPIRADA {
            get {
                return ResourceManager.GetString("SESSAO_EXPIRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido. Valores possíveis: {ValoresPossiveis}.
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status não pode ser vazio.
        /// </summary>
        public static string STATUS_VAZIO {
            get {
                return ResourceManager.GetString("STATUS_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expirado.
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido.
        /// </summary>
        public static string TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
